blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:pk>/', views.post_detail, name='post_detail'),
    path('new/', views.post_new, name='post_new'),
]

prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings                         # 추가 1
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('blog/', include('blog.urls')),
    path('pizzas/', include('pizzas.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:                                        # 추가 2
    import debug_toolbar                                  # 추가 2
    urlpatterns += [                                      # 추가 2
        path('__debug__/', include(debug_toolbar.urls)),  # 추가 2
    ]                                                     # 추가 2

blog/models.py
from django.db import models
from pytz import timezone  # 현지 시각 출력을 위하여
from django.conf import settings
from django.urls import reverse


def local_time(input_time):
    fmt = '%Y-%m-%d %H:%M'
    my_zone = timezone(settings.TIME_ZONE)
    my_local_time = input_time.astimezone(my_zone)
    return my_local_time.strftime(fmt)


class Post(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,  # 'auth.User'라고 쓰는 것보다 강추
        on_delete=models.CASCADE,
        # related_name='post_set',  # 기본 설정과 동일하므로 주석 처리
        related_name='posts',
        verbose_name='게시자',
    )
    # verbose_name: 관리자 화면 등에서 열 제목으로 사용될 속성
    # 관계 필드에서 첫 인자는 관계 대상 모델, verbose_name 키워드 인자로 처리
    # 관계 필드가 아닌 일반 필드의 (생략 가능한) 첫 인자는 verbose_name
    title = models.CharField('제목', max_length=100)
    content = models.TextField('내용')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tags = models.ManyToManyField('Tag', blank=True, related_name='tags')

    class Meta:
        ordering = ['-id']  # Post 객체의 기본 정렬 순서 지정

    def __str__(self):
        return self.title

    def short_content(self):
        if self.content:
            t = self.content[:20] + '...'   # content 속성의 일부만 반환
        else:
            t = '(내용 없음)'
        return t
    short_content.short_description = '간략 내용'

    def tagged(self):
        ts = self.tags.all()
        return '{' + ', '.join(map(str, ts)) + '}'
        # return ', '.join(ts) # 이건 에러(왜 에러인지 모르겠음)
        # if ts:
        #     tag_string = '{'
        #     for t in ts:  # M2M 속성은 관리자이지, 쿼리셋이 아님
        #         tag_string += t.name + ', '  # t가 아니라 t.name
        #     tag_string = tag_string[:len(tag_string)-2] + '}'
        #     # tag_string 후미 ', '를 '}'으로 치환
        # else:
        #     tag_string = '{ }'

        # return tag_string
    tagged.short_description = '태그 집합'
    # 클래스 메소드로 속성을 대신할 때, verbose_name 대신에 short_description

    def updated(self):
        return local_time(self.updated_at)
    updated.short_description = '수정 일시'

    def get_absolute_url(self):
        # return reverse('blog:post_detail', args=[self.pk])
        return reverse('blog:post_detail', kwargs={'pk': self.pk})


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name='comments', verbose_name='게시물')
    message = models.TextField('댓글')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-post__id', '-id']  # '-post__id', '-id'

    def __str__(self):
        return self.message

    def updated(self):
        return local_time(self.updated_at)
    updated.short_description = '수정 일시'


class Tag(models.Model):
    name = models.CharField('태그', max_length=100, unique=True)

    class Meta:
        ordering = ['-id']  # Tag 객체의 기본 정렬 순서 지정

    def __str__(self):
        return self.name

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Tag


def post_list(request):
    qs = Post.objects.all()
    return render(request, 'blog/post_list.html',
                  {'post_list': qs})


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    all_tag = Tag.objects.all()
    mystr = post.tagged()
    my_tag = {}
    for t in all_tag:
        # mystr에서 t.name을 발견한 위치를 my_tag 사전에 등록
        # 키는 t.name으로, 값은 (못 찾으면 -1, 찾으면 양수)
        my_tag[t.name] = str(mystr).find(t.name)
    return render(request, 'blog/post_detail.html',
                  {'post': post, 'my_tag': my_tag})


def post_new(request):
    print('request.GET:', request.GET)
    print('request.POST:', request.POST)
    print('request.FILES:', request.FILES)
    return render(request, 'shop/item_form.html')

blog/templates/blog/layout.html
{% extends 'layout.html' %} {# 프로젝트 수준 layout.html 템플릿을 상속받음 #}
{% block title %}
    {{ block.super }} blog
{% endblock %}
{% block extra_head %}
    <style>
        {# blog 관련 템플릿에만 적용할 CSS 정의 혹은 연결 #}
    </style>
{% endblock %}
{% block extra_body %}
    <script>
        {# blog 관련 템플릿에만 적용할 JS 정의 혹은 연결 #}
    </script>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends './layout.html' %}  {# '/blog/layout.html'로 하면 오류 #}

{% block content %}
<!--    <a href="/blog/">게시판 목록으로 돌아가기</a><br/><br/>-->
      <a href="{% url 'blog:post_list' %}">게시판 목록으로 돌아가기</a><br/><br/>
    <form>
    <fieldset>
    <table>
        <thead>
            <th>필드</th><th>내용</th>
        </thead>
        <tbody>
        <tr>
            <td width="10%">id:</td><td><input type="text" value={{ post.id }}></td>
        </tr>
        <tr>
            <td>게시자:</td><td><input type="text" value="{{ post.author }}"></td>
        </tr>
        <tr>
            <td>제목:</td><td><input type="text" value="{{ post.title }}" style="width:300px;"></td>
        </tr>
        <tr>
            <td>간략 내용:</td><td><input type="text" value="{{ post.short_content }}"  style="width:300px;"></td>
        </tr>
        <tr>
            <td>내용:</td>
            <td><textarea style="width: 400px; height: 200px; overflow: visible;">{{ post.content }}</textarea></td>
        </tr>
        <tr>
            <td>게시 일시:</td><td><input type="text" value="{{ post.created }}"></td>
        </tr>
        <tr>
            <td>수정 일시:</td><td><input type="text" value="{{ post.updated_at }}"></td>
        </tr>
        <tr>
            <td>태그 집합:</td><td><input type="text" value="{{ post.tagged }}"></td>
        </tr>
        </tbody>
    </table>
    </fieldset>
    </form> <br/>

    {# https://python.bakyeono.net/chapter-7-2.html #}
        `for key, value in my_tag.items`:
        {% for key, value in my_tag.items %}
            {% if value > 0 %}
                <input type="checkbox" name={{ key }} checked>
            {% else %}
                <input type="checkbox" name={{ key }}>
            {% endif %}
            <label for={{ key }}> {{ key }} </label>
        {% endfor %} <br/>
        <hr>
<table>
        <thead>
            <th>id</th>
            <th>댓글</th>
            <th>작성 일시</th>
            <th>수정 일시</th>
        </thead>
        <tbody>
        {% for c in post.comments.all %}
            <tr>
                <td>{{ c.id }}</td>
                <td>{{ c.message }}</td>
                <td>{{ c.created_at }}</td>
                <td>{{ c.updated }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


    post.tagged: {{ post.tagged }} <br/>
    post.tags.all: {{ post.tags.all }} <br/><br/>

    `for key, value in my_tag.items`: <br/>
    {% for key, value in my_tag.items %}
        키: {{ key }} 값: {{ value }} <br/>
    {% endfor %} <br/><br/>



   <form>
    <fieldset>
        id:         <input type="text" value={{ post.id }}> <br/>
        게시자:     <input type="text" value="{{ post.author }}"> <br/>
        제목:       <input type="text" value="{{ post.title }}"> <br/>
        간략 내용:  <input type="text" value="{{ post.short_content }}"> <br/>
        내용:       <input type="text" value="{{ post.content|linebreaksbr }}"> <br/>
        내용:       {{ post.content|linebreaksbr }} <br/>
        내용:       <textarea style="width: 200px; height: 200px;">{{ post.content }}</textarea> <br/>
        내용:       <textarea style="width: 200px; height: 200px;">{{ post.content|linebreaksbr }}</textarea> <br/>
        수정 일시:  <input type="text" value="{{ post.updated }}"> <br/>
        게시 일시:  <input type="text" value="{{ post.created_at }}"> <br/>
        태그 집합:  <input type="text" value="{{ post.tagged }}"> <br/>
    </fieldset>
    </form> <br/>

    post: {{ post.id }}#{{ post.author }}#{{ post.title }}#
            {{ post.short_content }}#{{ post.updated }}#
            {{ post.created_at }}#{{ post.tagged }}<br/><br/>

    id: {{ post.id }}<br/>
    게시자: {{ post.author }}<br/>
    제목: {{ post.title }}<br/>
    간략 내용: {{ post.short_content }}<br/>
    내용: {{ post.content|linebreaksbr }}<br/>
    수정 일시: {{ post.updated }}<br/>
    게시 일시: {{ post.created_at }}<br/>
    태그 집합: {{ post.tagged }}<br/><br/>

    post: {{ post }}<br/><br/>

    <hr>
    post.comments.all: {{ post.comments.all }} <br/><br/>

    post.comments.first: {{ post.comments.first }} <br/><br/>

    post.comments.last: {{ post.comments.last }} <br/><br/>

    for c in post.comments.all:<br/>
    {% for c in  post.comments.all %}
        {{ c }} <br/>
    {% endfor %}<br/>

    for c in post.comments.all:<br/>
    {% for c in  post.comments.all %}
            {{ c.id }}#{{ c.post }}#{{ c.message }}#{{ c.created_at }}#{{ c.updated }}<br/>
    {% endfor %}<br/>

{% endblock content %}

blog/templates/blog/post_list.html
{% extends '../layout.html' %}

{% block content %}
    <h5>post_list 통째로 출력</h5>
    post_list: {{ post_list }}<br/>

    <h5>post_list 내부의 post 통째로 출력</h5>
        {% for post in post_list %}
            post: {{ post }}<br/>
        {% endfor %}<br/>

    <h5>post_list 내부의 post 속성 출력</h5>
    {% for post in post_list %}
        post: {{ post.id }}#{{ post.author }}#{{ post.title }}#
            {{ post.content }}#{{ post.created_at }}#
            {{ post.updated_at }}#{{ post.tags }}<br/>
    {% endfor %}<br/>

    <h5>post_list 내부의 post 메소드 출력</h5>
    {% for post in post_list %}
        post: {{ post.id }}#{{ post.author }}#{{ post.title }}#
            {{ post.short_content }}#{{ post.updated }}#
            {{ post.updated_at }}#{{ post.tagged }}<br/>
            {% verbatim %} {{ post.id|add:1 }} {% endverbatim %}
                {{ post.id|add:1 }}<br/>
            {% verbatim %} {{ post.id|add:'love' }} {% endverbatim %}
                {{ post.id|add:'love' }}<br/>
            {% verbatim %} {{ post.id|add:"1" }} {% endverbatim %}
                {{ post.id|add:1 }} <br/>
            {% verbatim %} {{ post.tags.all }} {% endverbatim %}
                {{ post.tags.all }} <br/>
            {% verbatim %} {{ post.title|cut:" " }} {% endverbatim %}
                {{ post.title|cut:" " }} <br/>
            {% verbatim %}
                {{ post.tagged|cut:"{"|cut:"}"|default:"태그 없음" }}
            {% endverbatim %}
                {{ post.tagged|cut:"{"|cut:"}"|default:"태그 없음" }} <br/>
            {% verbatim %} { {{ post.tags.all|join:", " }} } {% endverbatim %}
                { {{ post.tags.all|join:", " }} } <br/>
            {% verbatim %} {{ post.content|linebreaks }} {% endverbatim %} <br/>
                {{ post.content|linebreaks }} <br/>
            {% verbatim %} {{ post.content|linebreaksbr }} {% endverbatim %}
                <br/>{{ post.content|linebreaksbr }} <br/>
            {% verbatim %} {{ post.author.email }} {% endverbatim %}
                {{ post.author.email }} <br/>
            {% verbatim %} {{ post.author.email|urlize }} {% endverbatim %}
                {{ post.author.email|urlize }} <br/>
            <br/>
    {% endfor %}<br/>

    <h5>post_list 테이블 형식 출력</h5>
    <table>
        <thead>
            <th>id</th>
            <th>게시자</th>
            <th>제목</th>
            <th>간략 내용</th>
            <th>작성 일시</th>
            <th>수정 일시</th>
            <th>태그 집합</th>
        </thead>
        <tbody>
        {% for post in post_list %}
        <tr style="background-color:
                {% ifchanged post.id %}
                    {% cycle 'yellow' 'pink' %}
                {% else %}
                    'gray'
                {% endifchanged %}"
        >
            <td>{{ post.id }}</td>
            <td>{{ post.author }}</td>
            <td>
               <a href="{{ post.get_absolute_url }} ">
<!--                <a href="/blog/{{ post.pk }}">-->
                    {# href="blog/..."로 하면 오류!!! #}
                    {{ post.title }}
                </a>
            </td>
            <td>{{ post.short_content }}</td>
            <td>{{ post.created }}</td>
            <td>{{ post.updated_at }}</td>
            <td>{{ post.tagged }}</td>
        </tr>
       {% endfor %}
        </tbody>
    </table><br/>
{% endblock %}