prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings                         # 추가 1
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('blog/', include('blog.urls')),
    path('pizzas/', include('pizzas.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:                                        # 추가 2
    import debug_toolbar                                  # 추가 2
    urlpatterns += [                                      # 추가 2
        path('__debug__/', include(debug_toolbar.urls)),  # 추가 2
    ]                                                     # 추가 2

shop/urls.py
from django.urls import path, register_converter
from shop import views
from shop import converters

app_name = 'shop'

register_converter(converters.FourDigitYearConverter, 'yyyy')

urlpatterns = [
    path('excel/', views.response_excel),
    path('image/', views.response_image),
    path('mysum/<int:x>/<int:y>/', views.my_sum),
    path('archives/<yyyy:year>/', views.year_archive),
    path('', views.item_list, name='item_list'),
    path('<int:pk>/', views.item_detail, name='item_detail'),
    path('test_templates/', views.test_templates),
    path('new/', views.item_new, name='item_new'),
    path('<int:pk>/edit/', views.item_edit, name='item_edit'),
]

shop/models.py
from django.db import models
from django.urls import reverse


class Item(models.Model):
    name = models.CharField(max_length=20)
    desc = models.TextField(blank=True)
    price = models.PositiveIntegerField(default=0)
    photo = models.ImageField(blank=True)
    is_published = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    review = models.TextField(blank=True) ###

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:item_detail', args=[self.pk])

shop/views.py
from django.shortcuts import render
from .models import Item
import requests
from PIL import Image, ImageDraw, ImageFont
import pandas as pd                           # 엑셀 요청 처리
from io import BytesIO
from urllib.parse import quote
import re
from django.http import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404


def response_excel(request):
    df = pd.DataFrame([
        [100, 110, 120],
        [200, 210, 220],
    ])

    io = BytesIO()
    df.to_excel(io)
    io.seek(0)

    encoded_filename = quote('pandas.xlsx')     # '.xls'가 아니라 '.xlsx'
    response = HttpResponse(io, content_type='application/vnd.ms-excel')
    response['Content-Disposition'] = \
        "attachment; filename*=utf-8''{}".format(encoded_filename)
    return response


def response_image(request):
    ttf_path = 'C:/Windows/Fonts/H2PORL.TTF'  # 윈도우, 맥: '/Library/Fonts/AppleGothic.ttf'

    # 이미지 파일 다운로드 혹은 로컬 디스크 상의 이미지 직접 열기
    image_url = 'http://www.flowermeaning.com/flower-pics/Calla-Lily-Meaning.jpg'
    res = requests.get(image_url)  # 서버로 HTTP GET 요청하여, 응답 획득
    io = BytesIO(res.content)  # 응답의 Raw Body 메모리 파일 객체 BytesIO 인스턴스 생성
    io.seek(0)  # 파일의 처음으로 커서를 이동

    canvas = Image.open(io).convert('RGBA')  # 이미지 파일을 열고, RGBA 모드로 변환
    font = ImageFont.truetype(ttf_path, 40)  # 지정 경로의 TrueType 폰트, 폰트 크기40
    draw = ImageDraw.Draw(canvas)  # canvas에 대한 ImageDraw 객체 획득

    text = 'Smart IT, by logistex'
    left, top = 400, 400
    margin = 10
    width, height = font.getsize(text)
    right = left + width + margin
    bottom = top + height + margin
    draw.rectangle((left, top, right, bottom), (255, 255, 224))
    draw.text((left+5, top+5), text, font=font, fill=(20, 20, 20))

    response = HttpResponse(content_type='image/png')
    canvas.save(response, format='PNG')  # HttpResponse의 유사 파일 객체 특성 활용
    return response


def year_archive(request, year):
    if year is not None:
        return HttpResponse('{}년도 자료 입니다.'.format(year))
    else:
        return HttpResponse('해당년도 자료는 없습니다.')


def my_sum(request, x, y):
    result = x + y
    output = '{} = {} + {}'.format(result, x, y)
    return HttpResponse(output)


def item_list(request):
    items = Item.objects.all()
    # return render(
    #     request,                    # 요청 정보
    #     'shop/item_list.html',    # 템플릿 이름
    #     {'item_list': items})      # 템플릿에 전달할 정보를 사전형태
    # request.GET 객체에게 키값이 'q'로 지정된 값을 요구해서 변수 q에 저장
    q = request.GET.get('q', '')  # 키값이 'q'로 지정된 값이 없으면 None이 반환됨
    if q:  # q가 널 아니면 qs에 filter 조건 추가
        items = items.filter(name__icontains=q)
    return render(request, 'shop/item_list.html', {
        'item_list': items,
        'q': q,
    })


def item_detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    return render(request, 'shop/item_detail.html',
                  {'item': item})


class MyClass:
    x = 10
    y = 20


def test_templates(requset):
    from django.template import Context, Template
    import datetime       # USE_TZ = True
    from django.utils import timezone   # TIME_ZONE = 'Asia/Seoul'
    from dateutil.parser import parse

    # 맥락 변수 사전
    my_dict = {'first_name': 'haewoong', 'last_name': 'Shin'}
    my_obj = MyClass()
    my_list = [1, 2, 3, 4]
    my_date = datetime.datetime.now()
    local_time = timezone.localtime()
    my_b_date1 = datetime.date(2019, 12, 29)
    my_b_date2 = parse('2010-12-29')
    my_b_datetime = datetime.datetime(2010, 12, 29, 17, 34, 56)
    my_string = '사랑하지 않으려면 떠나라. Love it or leave it.'

    context = Context({'my_dict': my_dict, 'my_obj': my_obj, 'my_list': my_list,
                       'my_date': my_date, 'local_time': local_time,
                       'my_b_date1': my_b_date1, 'my_b_date2': my_b_date2,
                       'my_b_datetime': my_b_datetime, 'my_string': my_string,
                       })
    template = Template(
        "사전 < my_dict.last_name >: {{ my_dict.last_name }} <br/>"
        + "객체 < my_obj.x >: {{ my_obj.x }} {{ my_obj.y }} <br/>"
        + "리스트 < my_list.0 >: {{ my_list.0 }} {{ my_list.2 }}: {{ my_list.2 }} <br/>"
        + "< my_dict.first_name|title >: {{ my_dict.first_name|title }} <br/>"
        + "{% verbatim myblock %}{% now 'Y-m-d H:i:s' %}"
        + "{% endverbatim myblock %} : {% now 'Y-m-d H:i:s' %} <br/>"
        + "< my_date > : {{ my_date }} <br/>"
        + "< local_time >: {{ local_time }} <br/>"
        + "< my_b_date1 >: {{ my_b_date1 }} <br/>"
        + "< my_b_date2 >: {{ my_b_date2 }} <br/>"
        + "< my_b_date1|date:'SHORT_DATE_FORMAT' >: {{ my_b_date1|date:'SHORT_DATE_FORMAT' }} <br/>"
        + "(마지막에 점이 찍힘!! 필터 내부에서 인수를 표시할 때 사용하는 \':\' 뒤에 띄우지 말 것!)<br/>"
        + "< my_b_date1|date:'Y년 m월 d일' >: {{ my_b_date1|date:'Y년 m월 d일' }} <br/>"
        # + "< my_b_date|date:'LONG_DATE_FORMAT' >(???)': {{ my_b_date|date:'LONG_DATE_FORMAT' }} <br/>"
        # + "(필터 내부에서 인수를 표시할 때 사용하는 \':\' 뒤에 띄우지 말 것!)<br/>" # 오류!!
        + "< my_b_datetime >: {{ my_b_datetime }} <br/>"
        + "< my_b_datetime|date:'Y년 m월 d일' > < my_b_datetime|time:'H시 i분 s초' >: "
        + "{{ my_b_datetime|date:'Y년 m월 d일' }}  {{ my_b_datetime|time:'H시 i분 s초' }} <br/>"
        + "(필터 내부에서 인수를 표시할 때 사용하는 \':\' 뒤에 띄우지 말 것!)<br/>"
        + "< my_string|lower|truncatewords:'4' >: {{ my_string|lower|truncatewords:'4' }} <br/>"
        + "< my_string|lower|truncatewords:4 >: {{ my_string|lower|truncatewords:4 }} <br/>"
        + "(필터 내부에서 인수를 표시할 때 사용하는 \':\' 뒤에 띄우지 말 것!)<br/>"
        + "< my_string|lower|truncatechars:'12' >: {{ my_string|lower|truncatechars:'12' }} <br/>"
        +"(필터 내부에서 인수를 표시할 때 사용하는 \':\' 뒤에 띄우지 말 것!)<br/>"
    )
    content = template.render(context)

    return HttpResponse(content)


# def item_new(request):
#     print('request.GET:', request.GET)
#     print('request.POST:', request.POST)
#     print('request.FILES:', request.FILES)
#     return render(request, 'shop/item_form.html')


def item_new(request, item=None):
    error_list = []
    initial = {}

    if request.method == 'POST':
        data = request.POST
        files = request.FILES

        name = data.get('name')
        desc = data.get('desc')
        price = data.get('price')
        photo = files.get('photo')
        is_published = data.get('is_published') in (True, 't', 'True', '1')
        review = data.get('review') ###

        # 유효성 검사
        if len(name) < 2:
            error_list.append('name을 2글자 이상 입력해주세요.')

        if re.match(r'^[\da-zA-Z\s]+$', desc):
            error_list.append('한글을 입력해주세요.')

        if not error_list:
            # 저장 시도
            if item is None:
                item = Item()

            item.name = name
            item.desc = desc
            item.price = price
            item.is_published = is_published
            if photo:
                item.photo.save(photo.name, photo, save=False)

            try:
                item.save()
            except Exception as e:
                error_list.append(e)
            else:
                return redirect('shop:item_list')

        initial = {
            'name': name,
            'desc': desc,
            'price': price,
            'photo': photo,
            'is_published': is_published,
            'review': item.review, ###
        }
    else:
        if item is not None:
            initial = {
                'name': item.name,
                'desc': item.desc,
                'price': item.price,
                'photo': item.photo,
                'is_published': item.is_published,
                'review':item.review,
            }
    return render(request, 'shop/item_form.html', {
        'error_list': error_list,
        'initial': initial,
    })


def item_edit(request, pk):
    item = get_object_or_404(Item, pk=pk)
    return item_new(request, item)


def item_review(request, pk):
    item = get_object_or_404(Item, pk=pk)
    return item_review(request, item)

shop/templates/shop/item_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>item_detail</title>
    <style>
        table {
          font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
          border-collapse: collapse;
          width: 100%;
        }

        table td, table th {
          border: 2px solid #6eb3dd;
          padding: 6px;
            text-align: center;
        }

        table tr:nth-child(even){background-color: #f2f2f2;}

        table tr:hover {background-color: #ffb8a5;}

        table th {
          padding-top: 12px;
          padding-bottom: 12px;
          text-align: left;
          background-color: #82ddda;
          color: white;
        }
    </style>
</head>
<body>
    <h3> 216230101 양우희</h3>
     <a href="{% url 'shop:item_list' %}"> 이전 페이지로 돌아가기 <- </a>
     <hr/>
    <table>

    <tbody>
        <tr>
            <td style="text-align: center; font-weight: bold; background-color: #82ddda; color: white">아이디</td>
            <td> {{ item.id }} </td>
        </tr>
        <tr>
            <td style="text-align: center; font-weight: bold; background-color: #82ddda; color: white">이름</td>
            <td> {{ item.name }} </td>
        </tr>
        <tr>
            <td style="text-align: center; font-weight: bold; background-color: #82ddda; color: white">설명</td>
            <td> {{ item.desc|linebreaksbr }} </td>
        </tr>
{#        <tr>#}
{#            <td>출시</td>#}
{#            <td> {{ item.is_published }} </td>#}
{#        </tr>#}
        <tr>
            <td style="text-align: center; font-weight: bold; background-color: #82ddda; color: white">등록 일시</td>
            <td> {{ item.created_at }} </td>
        </tr>
        <tr>
            <td style="text-align: center; font-weight: bold; background-color: #82ddda; color: white">수정 일시</td>
            <td> {{ item.updated_at }} </td>
        </tr>
        <tr>
            <td style="text-align: center; font-weight: bold; background-color: #82ddda; color: white">사진</td>
            <td> <img src="{{ item.photo.url }}" /> </td>
        </tr>

        <tr>
            <td style="text-align: center; font-weight: bold; background-color: #7addda; color: white">리뷰</td>
            <td> {{ item.review }} </td>
        </tr>
    </tbody>
    </table>
    {% for item in item_list %}
        {% if item.photo %}
            <img src="{{ item.photo.url }}" />
        {% endif %}
    {% endfor %}
</body>
</html>

shop/templates/shop/item_form.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
    <title>shop</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />
</head>
<body>
    <div class="container">
        <div class="col-sm-12">

            <h2>New Item</h2>

            {% if error_list %}
                <div class="alert alert-danger">
                    error_list: {{ error_list }}
                </div>
            {% endif %}

            {% if initial %}
                <div class="alert alert-info">
                    initial: {{ initial }}
                </div>
            {% endif %}

            <form action="" method="post" enctype="multipart/form-data" autocomplete="off">
                {% csrf_token %}

                <table class="table table-bordered">
                    <tbody>
                        <tr>
                            <th>name</th>
                            <td>
                                <input type="text" name="name" value="{{ initial.name }}" class="form-control" />
                            </td>
                        </tr>
                        <tr>
                            <th>desc</th>
                            <td>
                                <textarea name="desc" class="form-control">{{ initial.desc }}</textarea>
                            </td>
                        </tr>
                        <tr>
                            <th>price</th>
                            <td>
                                <input type="text" name="price" value="{{ initial.price }}" class="form-control" />
                            </td>
                        </tr>
                        <tr>
                            <th>photo</th>
                            <td>
                                <input type="file" name="photo" class="form-control" />
                            </td>
                        </tr>
                        <tr>
                            <th>is_published</th>
                            <td>
                                <input type="checkbox" name="is_published" value="1" {% if initial.is_published %}checked{% endif %} />
                            </td>
                        </tr>
                    </tbody>
                </table>

                <input type="submit" value="저장하기" class="btn btn-primary" />
            </form>

        </div>
    </div>
</body>
</html>

shop/templates/shop/item_list.html
{% extends './layout.html' %}
{% load static %}

{% block content %}
    {{ block.super }}
    <title>Shop</title>
    <form action="" method="GET">
        <input type="text" name="q" value="{{ q }}" />
        <input type="submit" value="검색" />
    </form>

</head>
<hr>
<body>
    {{ request }} <br/>
    request.method: {{ request.method }} <br/>
    request.GET: {{ request.GET }} <br/>
    request.META: {{ request.META }}
    <hr/>
    {{ item_list }}
    <hr>
    {% for item in item_list %}
        {{ item }} <br>
    {% endfor %}
    <hr>
    {% for item in item_list %}
        {{ item.name }} #
        {{ item.desc }} #
        {{ item.price }} #
        {{ item.created_at }} #
        {{ item.updated_at }}
        {{ item.review }} #
    {% endfor %}


    <hr>
    <table>
        <thead>
            <th>번호</th>
            <th>이름</th>
            <th>설명</th>
            <th>등록 일시</th>
            <th>수정 일시</th>
            <th>리뷰</th> ###
        </thead>
        <tbody>
            {% for item in item_list %}
            <tr>
                <td> {{ item.id }} </td>
                <td>
                    <a href="{% url 'shop:item_detail' pk=item.pk %}">
                        {{ item.name }}
                    </a>
                </td>
                <td>
                    <a href="{% url 'shop:item_edit' pk=item.pk %}">
                        {{ item.desc }}
                    </a>
                </td>
                <td> {{ item.created_at }} </td>
                <td> {{ item.updated_at }} </td>
                <td> {{ item.review }} </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>
{% endblock %}

shop/templates/shop/layout.html
{% extends '../layout.html' %}

{% load static %}

{% block title %}
    {{ block.super }} shop
{% endblock %}

{% block extra_head %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'shop/shop.css' %}" />
{% endblock %}

{% block content %}
    {{ block.super }}
    <img src="{% static 'shop/love.png' %}" alt="shop logo image">
    <h2>shop in yangwoohee site </h2>
{% endblock %}

{% block extra_body %}
    {{ block.super }}
    <script src="{% static 'shop/shop.js' %}"></script>
{% endblock %}